# Generated by Django 3.1.4 on 2022-08-09 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('phone_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('Bank', 'Bank'), ('BTC', 'BTC'), ('USDT', 'USDT')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('clientele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccount.clientele')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('referer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccount.clientele')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recovery_password', models.CharField(max_length=12)),
                ('time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('clientele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccount.clientele')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('Basic', 'Basic'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], max_length=10)),
                ('mode', models.CharField(choices=[('BTC', 'BTC'), ('USDT', 'USDT')], max_length=10)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('clientele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccount.clientele')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('BTC', 'BTC'), ('USDT', 'USDT')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('clientele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccount.clientele')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ref_bonus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_investments', models.IntegerField()),
                ('active_investments', models.IntegerField()),
                ('total_deposit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_withdrawal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('clientele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccount.clientele')),
            ],
        ),
    ]
