# Generated by Django 3.1.4 on 2022-08-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0002_auto_20220809_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='active_investments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='account',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='account',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='account',
            name='ref_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_investments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_withdrawal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
