# Generated by Django 3.1.4 on 2022-08-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0003_auto_20220809_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
