# Generated by Django 3.1.4 on 2022-08-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0004_auto_20220809_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='mode',
        ),
        migrations.AddField(
            model_name='investment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investment',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='mode',
            field=models.CharField(choices=[('BANK', 'BANK'), ('BTC', 'BTC'), ('USDT', 'USDT')], max_length=10),
        ),
    ]
