# Generated by Django 3.1.4 on 2022-08-15 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0005_auto_20220810_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='referer',
            new_name='referral',
        ),
        migrations.AlterField(
            model_name='investment',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Emailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailOTP', models.BooleanField(default=False)),
                ('emailProfit', models.BooleanField(default=True)),
                ('emaiInvest', models.BooleanField(default=True)),
                ('clientele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccount.clientele')),
            ],
        ),
    ]
