# Generated by Django 3.1.4 on 2022-08-16 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0006_auto_20220815_1548'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emailing',
        ),
    ]
