# Generated by Django 3.1.4 on 2022-08-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0007_delete_emailing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='referral',
            new_name='referer',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='referral',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
