# Generated by Django 3.2 on 2022-08-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0010_deposit_tid_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='investment',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
