# Generated by Django 3.2 on 2022-08-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0011_auto_20220826_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.FloatField(),
        ),
    ]
