# Generated by Django 3.2 on 2022-08-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0013_auto_20220826_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='profit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='ref_bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_deposit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_withdrawal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='referral',
            name='bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='referral',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
