# Generated by Django 3.2 on 2022-09-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0014_auto_20220826_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientele',
            name='passcode',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
